# API 1 
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "adam_richard123",
  "name": "Adam Richard",
  "password": "richard_567541",
  "gender": "male",
  "location": "Detroit"
}

###

# API 2
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567541"
}

###

# API 3
PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "adam_richard",
  "oldPassword": "richard_567",
  "newPassword": "richard@123"
}

###

